name: awesome_to_do
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.3.0
  build_runner: ^2.4.11
  cloud_firestore: ^5.1.0
  equatable: ^2.0.5
  firebase_app_check: ^0.3.0+3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^8.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
