name: awesome_to_do
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  auto_route: ^8.3.0
  bloc: ^8.1.4
  bot_toast: ^4.1.3
  build_runner: ^2.4.11
  cloud_firestore: ^5.1.0
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  firebase_app_check: ^0.3.0+3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.0.3
  firebase_storage: ^12.1.1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  intl: ^0.19.0
  logger: ^2.4.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  recase: ^4.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  universal_io: ^2.2.2
  uuid: ^4.4.2

dev_dependencies:
  auto_route_generator: ^8.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#CFD8DC"
    theme_color: "#CFD8DC"

flutter_native_splash:
  image: assets/images/logo.png
  color: "#CFD8DC"
  color_dark: "#CFD8DC"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#CFD8DC"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#CFD8DC"

  android_gravity: center
  web: true